### PR TITLE
fix: nest files with timestamp for plugin runners

### LINKED ISSUE #930: Plugin runner config and output path gets overridden in parallel mode
### What happened?

When running plugins in parallel or running same plugin multiple times for different audits it overrides its runner config as the folder for each individual runner config is `node_modules/.code-pushup/<plugin-name>`.

### What would you expect to happen?

Each runner of individual plugins should have its own unique folder to hold the config file and output file.
This can be achieved by adding one more level of nesting into runners folder as in `node_modules/.code-pushup/<timestamp>/<plugin-slug>`.

Also plugin slug should be used instead of hardcoded plugin name as it will be more versatile if people would reuse or extend existing plugins with their own variety (for example duplicating `coverage` plugin execution to get two reported coverages, one from Jest and one from Cypress component tests)

### What steps did you take?

1. Setup Code PushUp target with ESLint for multiple projects in one Nx monorepo
2. For better reproduction have different lint rules setup in the projects
3. Run plugins in parallel or via affected
4. Observe errors of rules not being found or other weird behavior related to overridden runner config

### Code PushUp package version

latest

### What operation system are you on?

Windows

### Node version

22

### Relevant log output

```shell

```

### PR DESCRIPTION
**Pull request by vmasek**
closes #930
part of #888 
part of #695
Additional changes:
- [x] makes sure all the logs from runner process will appear in CLI via logger `log`
- [x] adds some handy logs that help identify or reproduce issues
- [x] adds `--no-progress --verbose` to "code-pushup" command "node packages/cli/src/index.ts" that runns CP collection on this repo as it is very annoying to not have logs considering how frequently it is it breaks during PRs

### CODE REVIEW

File: packages/core/src/lib/implementation/runner.ts [hunk 1]
```diff
@@ -26,7 +31,8 @@ export async function executeRunnerConfig(
   });
 
   // read process output from file system and parse it
-  const outputs = await readJsonFile(path.join(process.cwd(), outputFile));
+  const outputs = await readJsonFile(outputFile);
+  await removeDirectoryIfExists(path.dirname(outputFile));
```
Comment (matejchalk) [inline packages/core/src/lib/implementation/runner.ts:35]: This deserves a comment, took me a while to realize why you remove the directory after reading.

```suggestion
  // clean up plugin output directory
  await removeDirectoryIfExists(path.dirname(outputFile));
```

File: packages/plugin-eslint/src/bin.ts [hunk 2]
```diff
@@ -1,3 +1,7 @@
+import process from 'node:process';
+import { Parser } from 'yargs/helpers';
 import { executeRunner } from './lib/runner/index.js';
 
-await executeRunner();
+const { runnerConfigPath, runnerOutputPath } = Parser(process.argv);
```
Comment (matejchalk) [inline packages/plugin-eslint/src/bin.ts:5]: Why don't we declare the required Yargs options? Then the args will actually be validated, and we'll get the inferred types.

The logic could live in `@code-pushup/utils`, since many plugins are using the same pattern.

File: packages/plugin-eslint/src/lib/eslint-plugin.integration.test.ts [hunk 3]
```diff
@@ -18,10 +19,19 @@ describe('eslintPlugin', () => {
...
+      args: (plugin.runner as RunnerConfig).args?.map(arg => {
+        if (arg.includes('bin.js')) {
+          return toUnixPath(arg.replace(path.dirname(thisDir), '<dirname>'));
+        }
+
+        return toUnixPath(arg).replace(
+          /\/eslint\/\d+\//,
+          '/eslint/<timestamp>/',
+        );
+      }),
```
Comment (matejchalk) [inline packages/plugin-eslint/src/lib/eslint-plugin.integration.test.ts:31]: This can be simplified:

```suggestion
      args: (plugin.runner as RunnerConfig).args?.map(arg =>
        toUnixPath(arg.replace(path.dirname(thisDir), '<dirname>')).replace(
          /\/eslint\/\d+\//,
          '/eslint/<timestamp>/',
        ),
      ),
```

File: packages/plugin-eslint/src/lib/runner.integration.test.ts [hunk 4]
```diff
@@ -2,26 +2,36 @@ import os from 'node:os';
...
     const targets: ESLintTarget[] = [{ eslintrc, patterns }];
     const { audits } = await listAuditsAndGroups(targets);
-    await createRunnerConfig('bin.js', audits, targets);
+    const { outputFile } = await createRunnerConfig('bin.js', audits, targets);
+    return {
+      runnerOutputPath: outputFile,
+      runnerConfigPath: outputFile.replace(
+        'runner-output.json',
+        'plugin-config.json',
+      ),
```
Comment (matejchalk) [inline packages/plugin-eslint/src/lib/runner.integration.test.ts:33]: Maybe we could add an optional `configFile` to the runner config schema? It would save you from doing this output file replacement in several tests. And the core could then also take care of deleting the config file as well :thinking:

File: packages/utils/src/lib/execute-process.ts [hunk 5]
```diff
@@ -148,6 +150,9 @@ export function executeProcess(cfg: ProcessConfig): Promise<ProcessResult> {
   const date = new Date().toISOString();
   const start = performance.now();
 
+  const logCommand = [command, ...(args || [])].join(' ');
+  ui().logger.log(gray(`Executing command:\n${logCommand}`));
```
Comment (matejchalk) [inline packages/utils/src/lib/execute-process.ts:154]: Nice improvement, adds a lot more transparency :+1:

File: project.json [hunk 6]
```diff
@@ -5,7 +5,7 @@
     "code-pushup": {
       "executor": "nx:run-commands",
       "options": {
-        "command": "node packages/cli/src/index.ts",
+        "command": "node packages/cli/src/index.ts --no-progress --verbose",
```
Comment (matejchalk) [inline project.json:8]: :+1:

**Review by matejchalk — APPROVED** [review]
Thank you for taking care of this :slightly_smiling_face: 

Left some suggestions, but none of them are a blocker.

File: packages/plugin-eslint/src/lib/nx.integration.test.ts [hunk 7]
```diff
@@ -11,7 +12,7 @@ import {
 
 type Project = 'cli' | 'core' | 'nx-plugin' | 'utils';
 
-describe('Nx helpers', () => {
+describe.skipIf(() => process.platform === 'win32')('Nx helpers', () => {
```
[the remark this answers is not in the document]
Comment (vmasek) [reply packages/plugin-eslint/src/lib/nx.integration.test.ts:15]: For some reason type signature suggested the Fn, I'll fix it

**Review by matejchalk — APPROVED** [review]
