### PR TITLE
chore(utils): fix ESLint issues, loosen perf ESLint rules

### LINKED ISSUE #261: lint fixes in utils
- [ ] fix all lint errors and warnings in `utils` package
  - apart from FP rules `no-param-reassign`, `functional/immutable-data` and  `functional/no-let`, those will be fixed in #260 
- [ ] if a rule doesn't fail anymore for other packages, remove the `"off"` rule entry from last override in `.eslintrc.json`

## How to fix failing rules

Requiring manual attention:
- [no-magic-numbers](https://eslint.org/docs/latest/rules/no-magic-numbers)
  - move into named constants (e.g. `const MAX_SLUG_LENGTH = 128`)
- [no-console](https://eslint.org/docs/latest/rules/no-console)
  - if intended to be printed to stdout, use `console.info`, otherwise remove (`console.log` for debugging shouldn't be committed) 
- [@typescript-eslint/no-shadow](https://typescript-eslint.io/rules/no-shadow/)
  - rename variables to non-conflicting names
- [@typescript-eslint/no-unnecessary-condition](https://typescript-eslint.io/rules/no-unnecessary-condition/)
  - remove unneeded `?.` and `||` operators
- [sonarjs/no-duplicate-string](https://github.com/SonarSource/eslint-plugin-sonarjs/blob/master/docs/rules/no-duplicate-string.md)
  - define a constant
 - [unicorn/import-style](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/v48.0.1/docs/rules/import-style.md) 
   - e.g. `import { join } from 'path'` and `join(...)` ➡ `import path from 'node:path'` and `path.join()` 
 - [unicorn/prefer-string-replace-all](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/v48.0.1/docs/rules/prefer-string-replace-all.md)
   - autofixable, but requires changing `lib` in `tsconfig.base.json` to `es2021` 
- [@typescript-eslint/dot-notation](https://typescript-eslint.io/rules/dot-notation/)
  - autofixable, but usage in `progress.spec.ts` accesses private property 

Autofixable:
- [arrow-body-style](https://eslint.org/docs/latest/rules/arrow-body-style)
- [prefer-template](https://eslint.org/docs/latest/rules/prefer-template)
- [curly](https://eslint.org/docs/latest/rules/curly)
- [@typescript-eslint/prefer-nullish-coalescing](https://typescript-eslint.io/rules/prefer-nullish-coalescing/)
- [@typescript-eslint/consistent-type-definitions](https://typescript-eslint.io/rules/consistent-type-definitions/)
- [import/no-useless-path-segments](https://github.com/import-js/eslint-plugin-import/blob/v2.27.5/docs/rules/no-useless-path-segments.md)
- [unicorn/prefer-node-protocol](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/v48.0.1/docs/rules/prefer-node-protocol.md)
- [unicorn/consistent-destructuring](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/v48.0.1/docs/rules/consistent-destructuring.md)
- [unicorn/prefer-ternary](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/v48.0.1/docs/rules/prefer-ternary.md)
- [unicorn/prefer-number-properties](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/v48.0.1/docs/rules/prefer-number-properties.md)
- [unicorn/explicit-length-check](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/v48.0.1/docs/rules/explicit-length-check.md)
- [unicorn/numeric-separators-style](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/v48.0.1/docs/rules/numeric-separators-style.md)
- [unicorn/better-regex](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/v48.0.1/docs/rules/better-regex.md)
- [unicorn/prefer-spread](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/v48.0.1/docs/rules/prefer-spread.md)
- [unicorn/prefer-logical-operator-over-ternary](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/v48.0.1/docs/rules/prefer-logical-operator-over-ternary.md)
- [unicorn/no-new-array](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/v48.0.1/docs/rules/no-new-array.md)
  - use suggestion in IDE 
- [unicorn/no-negated-condition](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/v48.0.1/docs/rules/no-negated-condition.md)

### LINKED ISSUE #270: lint fixes in utils (6/7) - naming convention
- [x] fix all lint errors and warnings related to the `naming-convention` rule
- [x] if a rule doesn't fail anymore for other packages, remove the `"off"` rule entry from last override in `.eslintrc.json`

## Current errors and warnings

Image

## How to fix failing rules

- [@typescript-eslint/naming-convention](https://typescript-eslint.io/rules/naming-convention/)
  - rename as needed

### PR DESCRIPTION
**Pull request by Tlacenka**
Closes #261 
Closes #270 

This PR is part 1 of utils ESLint issues. I mostly fixed unicorn and sonarjs issues.
I also loosened ruleset for `perf` folder as its nature is more experimental.

Before:
image

[After](https://quality-metrics-staging.web.app/portal/code-pushup/cli/branch/eslint-utils-fixes/dashboard):
image

### CODE REVIEW

File: packages/utils/src/lib/reports/md/table.ts [hunk 1]
```diff
@@ -21,22 +21,30 @@ export function tableMd(
   if (data.length === 0) {
     throw new Error("Data can't be empty");
   }
-  align = align || data[0]?.map(() => 'c');
-  const _data = data.map(arr => '|' + arr.join('|') + '|');
-  const secondRow = '|' + align?.map(s => alignString.get(s)).join('|') + '|';
-  return _data.shift() + NEW_LINE + secondRow + NEW_LINE + _data.join(NEW_LINE);
+  align = align ?? data[0]?.map(() => 'c');
```
Comment (matejchalk) [inline packages/utils/src/lib/reports/md/table.ts:24]:
```suggestion
  align ??= data[0]?.map(() => 'c');
```

File: packages/utils/src/lib/reports/sorting.ts [hunk 2]
```diff
@@ -60,7 +60,7 @@ export function sortReport(report: ScoredReport): ScoredReport {
       ...audit,
       details: {
         ...audit.details,
-        issues: audit?.details?.issues.slice().sort(compareIssues) || [],
+        issues: [...(audit?.details?.issues ?? [])].sort(compareIssues),
```
Comment (matejchalk) [inline packages/utils/src/lib/reports/sorting.ts:63]: I'm not sure about this, the sorting will add en empty `issues` array even when one wasn't produced. I see it was also always creating a `details` object even if there wasn't one originally. Semantically there may not be much of a difference (although `issues: []` to me indicates that this audit _could_ produce issues), but it could bloat the JSON file size needlessly, and I wouldn't expect sorting to have this effect.

I'd suggest a softer approach. If `issues` aren't defined, just leave the original object unchanged:

```ts
audit =>
  audit.details?.issues
    ? { ...audit, details: { ...audit.details, issues: [...audit.details.issues].sort(compareIssues) } }
    : audit
```

File: packages/utils/src/lib/reports/sorting.ts [hunk 3]
```diff
@@ -60,7 +60,7 @@ export function sortReport(report: ScoredReport): ScoredReport {
       ...audit,
```
Comment (matejchalk) [inline packages/utils/src/lib/reports/sorting.ts:60]: The line above (can't click it) - `plugin.audits.sort(compareAudits)` - why does that not get flagged? It mutates `plugin` :sweat_smile:

File: packages/utils/src/lib/reports/utils.ts [hunk 4]
```diff
@@ -95,7 +95,7 @@ export function getSeverityIcon(
 }
 
 export function calcDuration(start: number, stop?: number): number {
-  stop = stop !== undefined ? stop : performance.now();
+  stop = stop ?? performance.now();
```
Comment (matejchalk) [inline packages/utils/src/lib/reports/utils.ts:98]:
```suggestion
  stop ??= performance.now();
```

File: packages/utils/src/lib/reports/utils.ts [hunk 5]
```diff
@@ -112,21 +112,15 @@ export function countCategoryAudits(
...
-              return {
-                ...groupLookup,
-                [group.slug]: group,
-              };
-            },
-            {},
+          ...Object.fromEntries(
+            plugin.groups.map(group => [group.slug, group]),
           ),
         },
```
Comment (matejchalk) [inline packages/utils/src/lib/reports/utils.ts:125]: Notice that this spreads into an otherwise empty object.

```ts
[plugin.slug]: {
   ...Object.fromEntries(...),
}
```

Can be simplified:

```ts
[plugin.slug]: Object.fromEntries(...),
```

**Review by matejchalk — COMMENTED** [review]
Came across some more minor things as I was reading this code :angel:

File: packages/utils/src/lib/reports/sorting.ts (hunk 3 above)
Comment (Tlacenka) [reply packages/utils/src/lib/reports/sorting.ts:60]: Because `immutable-data` is not enabled yet.
Either way, fixed.

File: packages/utils/src/lib/reports/utils.ts (hunk 5 above)
Comment (Tlacenka) [reply packages/utils/src/lib/reports/utils.ts:125]: Good point

**Review by matejchalk — APPROVED** [review]
